/////////////////////////////////////////////////////////////////////
// Attributeids.inc
//
// Contains all the attributeids for the attributes system
// those must fit the names defined in attributes.cfg
/////////////////////////////////////////////////////////////////////

// Attribute ids for skills
/*
const ATTRIBUTEID_ALCHEMY		:= "alchemy";
const ATTRIBUTEID_ANATOMY		:= "anatomy";
const ATTRIBUTEID_ANIMALLORE		:= "animallore";
const ATTRIBUTEID_ARCHERY		:= "archery";
const ATTRIBUTEID_ARMSLORE		:= "armslore";
const ATTRIBUTEID_BEGGING		:= "begging";
const ATTRIBUTEID_BLACKSMITHY		:= "blacksmithy";
const ATTRIBUTEID_BOWCRAFT		:= "bowcraft";
const ATTRIBUTEID_CAMPING		:= "camping";
const ATTRIBUTEID_CARPENTRY		:= "carpentry";
const ATTRIBUTEID_CARTOGRAPHY		:= "cartography";
const ATTRIBUTEID_COOKING		:= "cooking";
const ATTRIBUTEID_DETECTINGHIDDEN	:= "detectinghidden";
const ATTRIBUTEID_ENTICEMENT		:= "enticement";
const ATTRIBUTEID_EVALINT		:= "evaluatingintelligence";
const ATTRIBUTEID_FENCING		:= "fencing";
const ATTRIBUTEID_FISHING		:= "fishing";
const ATTRIBUTEID_FORENSICS		:= "forensicevaluation";
const ATTRIBUTEID_HEALING		:= "healing";
const ATTRIBUTEID_HERDING		:= "herding";
const ATTRIBUTEID_HIDING		:= "hiding";
const ATTRIBUTEID_INSCRIPTION		:= "inscription";
const ATTRIBUTEID_ITEMID		:= "itemId";
const ATTRIBUTEID_LOCKPICKING		:= "lockpicking";
const ATTRIBUTEID_LUMBERJACKING		:= "lumberjacking";
const ATTRIBUTEID_MACEFIGHTING		:= "macefighting";
const ATTRIBUTEID_MAGERY		:= "magery";
const ATTRIBUTEID_MAGICRESISTANCE	:= "magicresistance";
const ATTRIBUTEID_MEDITATION		:= "meditation";
const ATTRIBUTEID_MINING		:= "mining";
const ATTRIBUTEID_MUSICIANSHIP		:= "musicianship";
const ATTRIBUTEID_PARRY			:= "parry";
const ATTRIBUTEID_PEACEMAKING		:= "peacemaking";
const ATTRIBUTEID_POISONING		:= "poisoning";
const ATTRIBUTEID_PROVOCATION		:= "provocation";
const ATTRIBUTEID_REMOVETRAP		:= "removetrap";
const ATTRIBUTEID_SNOOPING		:= "snooping";
const ATTRIBUTEID_SPIRITSPEAK		:= "spiritspeak";
const ATTRIBUTEID_STEALING		:= "stealing";
const ATTRIBUTEID_STEALTH		:= "stealth";
const ATTRIBUTEID_SWORDSMANSHIP		:= "swordsmanship";
const ATTRIBUTEID_TACTICS		:= "tactics";
const ATTRIBUTEID_TAILORING		:= "tailoring";
const ATTRIBUTEID_TAMING		:= "animaltaming";
const ATTRIBUTEID_TASTEID		:= "tasteidentification";
const ATTRIBUTEID_TINKERING		:= "tinkering";
const ATTRIBUTEID_TRACKING		:= "tracking";
const ATTRIBUTEID_VETERINARY		:= "veterinary";
const ATTRIBUTEID_WRESTLING		:= "wrestling";


// Attribute ids for stats
const ATTRIBUTEID_DEXTERITY		:= "dexterity";
const ATTRIBUTEID_INTELLIGENCE		:= "intelligence";
const ATTRIBUTEID_STRENGTH		:= "strength";
*/