///////////////////////////////////////////////////////////
//
// Cfgfiles.inc
// 
// Constants for all the possible cfg files.
///////////////////////////////////////////////////////////


const CFGFILE_AREAS			:= ":areas:areas";
const CFGFILE_ATTRIBUTES_ALL		:= ":hook:attributes";
const CFGFILE_BOOKS_ZULU		:= ":sysbook:zulubooks";
const CFGFILE_CIRCLES			:= ":*:circles";
const CFGFILE_ENCHANTABLE_ITEMS		:= ":combat:enchantableitems";
const CFGFILE_ENCHANTMENTS		:= ":combat:modenchantdesc";
const CFGFILE_EQUIPMENT_STARTING	:= ":*:starteqp";
const CFGFILE_FOOD			:= ":*:food";
const CFGFILE_HITSCRIPTS		:= ":combat:hitscriptdesc";
const CFGFILE_INSCRIPTION		:= ":inscription:inscription";
const CFGFILE_ITEMS_ALL			:= ":*:itemdesc";
const CFGFILE_ITEMS_ALCHEMY		:= ":alchemy:itemdesc";
const CFGFILE_ITEMS_BLACKSMITHY		:= ":combat:itemdesc";
const CFGFILE_ITEMS_CARPENTRY		:= ":carpentry:itemdesc";
const CFGFILE_ITEMS_COOKING		:= ":cooking:itemdesc";
const CFGFILE_ITEMS_HOUSING		:= ":housing:itemdesc";
const CFGFILE_ITEMS_LUMBERJACKING	:= ":lumberjacking:itemdesc";
const CFGFILE_ITEMS_MINING		:= ":mining:itemdesc";
const CFGFILE_ITEMS_TAILORING		:= ":tailoring:itemdesc";
const CFGFILE_ITEMS_TELEPORTERS		:= ":teleporters:itemdesc";
const CFGFILE_ITEMS_TINKERING		:= ":tinkering:itemdesc";
const CFGFILE_KARMA_TITLES		:= ":*:titles";
const CFGFILE_LOCK_DIFFICULTIES		:= ":lockpicking:lockpicking";
const CFGFILE_LOOT_GROUPS		:= ":*:lootgroups";
const CFGFILE_MERCHANT_STOCKS		:= ":*:mrcspawn";
const CFGFILE_MOONGATES			:= ":teleporters:moongates";
const CFGFILE_NAMES			:= ":*:names";
const CFGFILE_NPCS			:= ":*:npcdesc";
const CFGFILE_ONHITSCRIPTS		:= ":combat:onhitscriptdesc";
const CFGFILE_PILLARS			:= ":teleporters:pillars";
const CFGFILE_POISON_DATA		:= ":mods:poison";
const CFGFILE_REAGENT_NAMES		:= ":*:reagentsxlate";
const CFGFILE_SHAPESHIFT		:= ":earth:shapeshift";
const CFGFILE_SHRINES			:= ":shrines:shrines";
const CFGFILE_SKILLS_ALL		:= ":*:skills";
const CFGFILE_SPELLS_ALL		:= ":*:spells";
const CFGFILE_SPELLS_EARTH		:= ":earth:spells";
const CFGFILE_SPELLS_NECROMANCY		:= ":necro:spells";
const CFGFILE_SPELLS_NORMAL		:= ":spells:spells";
const CFGFILE_TELEPORTERS		:= ":teleporters:teleporters";
const CFGFILE_TRACKING			:= ":tracking:tracking";
const CFGFILE_WEAPON_WRESTLING		:= ":*:wepndesc";
