///////////////////////////////////////////////////////////
// CIDs.inc
//
// Creature graphic IDs for the mobiles.
// Template CID_<desc>
// Those are hardcoded in the client don't modify them.
//
// TODO : Add the CIDs for equipement
///////////////////////////////////////////////////////////


// Creature IDs for the creatures
const CID_ALIGATOR		:= 0x00ca;
const CID_BEAR_DARK_BROWN	:= 0x00d3;
const CID_BEAR_LIGHT_BROWN	:= 0x00d4;
const CID_BEAR_POLAR		:= 0x00d5;
const CID_BIRD			:= 0x0006;
const CID_BLADE_SPIRIT		:= 0x023e;
const CID_BOAR			:= 0x0122;
const CID_BULL_BLACK_AND_WHITE	:= 0x00e9;
const CID_BULL_BROWN		:= 0x00e8;
const CID_BULLFROG		:= 0x0051;
const CID_BUNNY			:= 0x00cd;
const CID_CAT			:= 0x00c9;
const CID_CHICKEN		:= 0x00d0;
const CID_CORPSER		:= 0x0008;
const CID_COW_BLACK_AND_WHITE	:= 0x00d8;
const CID_COW_BROWN		:= 0x00e7;
const CID_CYCLOPS		:= 0x004c;
const CID_DAEMON_UNARMED	:= 0x0009;
const CID_DAEMON_WITH_SWORD	:= 0x000a;
const CID_DEER			:= 0x00ed;
const CID_DOG			:= 0x00d9;
const CID_DOLPHIN		:= 0x0097;
const CID_DUPRE			:= 0x03e2;
const CID_DRAGON_GRAY		:= 0x000c;
const CID_DRAGON_RED		:= 0x003b;
const CID_DRAKE_GRAY		:= 0x003c;
const CID_DRAKE_RED		:= 0x003d;
const CID_EAGLE			:= 0x0005;
const CID_ELEMENTAL_AIR		:= 0x000d;
const CID_ELEMENTAL_EARTH	:= 0x000e;
const CID_ELEMENTAL_FIRE	:= 0x000f;
const CID_ELEMENTAL_WATER	:= 0x0010;
const CID_ENERGY_VORTEX		:= 0x023d;
const CID_ETTIN			:= 0x0002;
const CID_ETTIN_WITH_HAMMER	:= 0x0012;
const CID_GARGOYLE		:= 0x0004;
const CID_GAZER			:= 0x0016;
const CID_GHOST_MALE		:= 0x0192;
const CID_GHOST_FEMALE		:= 0x0193;
const CID_GIANT_TOAD		:= 0x0050;
const CID_GM			:= 0x03db;
const CID_GOAT			:= 0x00d1;
const CID_GORILLA		:= 0x001d;
const CID_GREAT_HART		:= 0x00ea;
const CID_HARPY			:= 0x001e;
const CID_HEADLESS		:= 0x001f;
const CID_HORSE_DARK_BROWN	:= 0x00cc;
const CID_HORSE_GRAY_BROWN	:= 0x00e4;
const CID_HORSE_LIGHT_BROWN	:= 0x00c8;
const CID_HORSE_LIGHT_GRAY	:= 0x00e2;
const CID_HORSE_PACK		:= 0x0123;
const CID_HUMAN_MALE		:= 0x0190;
const CID_HUMAN_FEMALE		:= 0x0191;
const CID_LAVA_LIZARD		:= 0x00ce;
const CID_LICHE			:= 0x0018;
const CID_LIZARDMAN_UNARMED	:= 0x0021;
const CID_LIZARDMAN_WITH_MACE	:= 0x0024;
const CID_LIZARDMAN_WITH_SPEAR	:= 0x0023;
const CID_LLAMA			:= 0x00dc;
const CID_LLAMA_PACK		:= 0x0124;
const CID_LORD_BLACKTHORN	:= 0x03df;
const CID_LORD_BRITISH		:= 0x03de;
const CID_MONGBAT		:= 0x0027;
const CID_OGRE			:= 0x0001;
const CID_OPHIDIAN_MAGE		:= 0x0055;
const CID_OPHIDIAN_QUEEN	:= 0x0057;
const CID_OPHIDIAN_WARRIOR	:= 0x0056;
const CID_ORC_CAPTAIN		:= 0x0007;
const CID_ORC_UNARMED		:= 0x0011;
const CID_ORC_WITH_CLUB		:= 0x0029;
const CID_OSTARD_DESERT		:= 0x00d2;
const CID_OSTARD_FOREST		:= 0x00db;
const CID_OSTARD_FRENZIED	:= 0x00da;
const CID_PANTHER		:= 0x00d6;
const CID_PIG			:= 0x00cb;
const CID_RAT			:= 0x00ee;
const CID_RAT_GIANT		:= 0x00d7;
const CID_RATMAN_UNARMED	:= 0x002a;
const CID_RATMAN_WITH_AXE	:= 0x002c;
const CID_RATMAN_WITH_SWORD	:= 0x002d;
const CID_REAPER		:= 0x002f;
const CID_SCORPION_GIANT	:= 0x0030;
const CID_SERPENT_GIANT		:= 0x0015;
const CID_SERPENT_SEA		:= 0x0096;
const CID_SHEEP_SHEARED		:= 0x00df;
const CID_SHEEP_UNSHEARED	:= 0x00cf;
const CID_SKELETON_UNARMED	:= 0x0032;
const CID_SKELETON_WITH_AXE	:= 0x0038;
const CID_SKELETON_WITH_SCIMITAR:= 0x0039;
const CID_SLIME			:= 0x0033;
const CID_SNAKE			:= 0x0034;
const CID_SPECTRE		:= 0x001a;
const CID_SPIDER_GIANT		:= 0x001c;
const CID_TERATHAN_DRONE	:= 0x0047;
const CID_TERATHAN_MATRIARCH	:= 0x0048;
const CID_TERATHAN_WARRIOR	:= 0x0046;
const CID_TITAN			:= 0x004b;
const CID_TROLL_UNARMED		:= 0x0036;
const CID_TROLL_WITH_AXE	:= 0x0035;
const CID_TROLL_WITH_MAUL	:= 0x0037;
const CID_UNKNOWN_SEA_CREATURE	:= 0x005f;
const CID_WALRUS		:= 0x00dd;
const CID_WISP			:= 0x003a;
const CID_WOLF			:= 0x00e1;
const CID_ZOMBIE		:= 0x0003;


