/////////////////////////////////////////////////////////////////////
// Facings.inc
//
// Contain the facings values
/////////////////////////////////////////////////////////////////////


const FACING_NORTH		:= 0x0;
const FACING_NORTH_EAST		:= 0x1;
const FACING_EAST		:= 0x2;
const FACING_SOUTH_EAST		:= 0x3;
const FACING_SOUTH		:= 0x4;
const FACING_SOUTH_WEST		:= 0x5;
const FACING_WEST		:= 0x6;
const FACING_NORTH_WEST		:= 0x7;