///////////////////////////////////////////////////////////
//
// Fonts.inc
// 
// Constants for all the possible fonts.
///////////////////////////////////////////////////////////


const FONT_MIN          :=  0x00;   // Highest font.
const FONT_MAX          :=  0x09;   // Lowest font.

////
// Fonts
////
const FONT_BOLD			:=  0x00;   // Bold text.
const FONT_SHADOW		:=  0x01;   // Text with shadow.
const FONT_BOLD_SHAD		:=  0x02;   // Bold text with shadow.
const FONT_NORMAL		:=  0x03;   // Normal (default).
const FONT_GOTHIC		:=  0x04;   // Gothic.
const FONT_ITALIC		:=  0x05;   // Italic.
const FONT_SMALL_DARK		:=  0x06;   // Small dark letters.
const FONT_COLOR		:=  0x07;   // Colorful font.
const FONT_RUNE			:=  0x08;   // Rune font (only capitals).
const FONT_SMALL_LIGHT		:=  0x09;   // Small light letters.

////
// Font Colours
////
const FONTCOLOR_RED		:= 0x0026;
const FONTCOLOR_GREEN		:= 0x0044;
const FONTCOLOR_BLUE		:= 0x005a;
const FONTCOLOR_MAUVE		:= 0x001e;
const FONTCOLOR_LAVENDER	:= 0x0014;
const FONTCOLOR_BLACK		:= 0x0001;
const FONTCOLOR_BROWN		:= 0x002e;
const FONTCOLOR_YELLOW		:= 0x0035;