///////////////////////////////////////////////////////////
//
// Hitscripts.inc
// 
// Constants for all the hitscripts
///////////////////////////////////////////////////////////

const HITSCRIPT_MAIN		:= 0x0;
const HITSCRIPT_BANISHING	:= 0x1;
const HITSCRIPT_BLACKROCK	:= 0x2;
const HITSCRIPT_BLINDING	:= 0x3;
const HITSCRIPT_DRAIN_LIFE	:= 0x4;
const HITSCRIPT_DRAIN_MANA	:= 0x5;
const HITSCRIPT_DRAIN_STAMINA	:= 0x6;
const HITSCRIPT_INSTA_KILL	:= 0x7;
const HITSCRIPT_PARALYZE	:= 0x8;
const HITSCRIPT_PIERCING	:= 0x9;
const HITSCRIPT_POISON		:= 0xa;
const HITSCRIPT_SLAYER		:= 0xb;
const HITSCRIPT_SPELL_CASTING	:= 0xc;
const HITSCRIPT_TRI_ELEMENTAL	:= 0xd;
const HITSCRIPT_VOID		:= 0xe;