///////////////////////////////////////////////////////////
// LandTiles.inc
//
// Constants for landtiles.
///////////////////////////////////////////////////////////


const LANDTILE_DIRT_START1	:= 0x0071;
const LANDTILE_DIRT_END1	:= 0x007c;
const LANDTILE_DIRT_START2	:= 0x0082;
const LANDTILE_DIRT_END2	:= 0x00a7;
const LANDTILE_DIRT_START3	:= 0x00dc;
const LANDTILE_DIRT_END3	:= 0x00e3;
const LANDTILE_DIRT_START4	:= 0x00e8;
const LANDTILE_DIRT_END4	:= 0x00eb;
const LANDTILE_FOREST_START	:= 0x00c4;
const LANDTILE_FOREST_END	:= 0x00d7;
const LANDTILE_FURROWS_START	:= 0x0009;
const LANDTILE_FURROWS_END	:= 0x0015;
const LANDTILE_GRASS_START1	:= 0x0003;
const LANDTILE_GRASS_END1	:= 0x0006;
const LANDTILE_GRASS_START2	:= 0x007d;
const LANDTILE_GRASS_END2	:= 0x007e;
const LANDTILE_GRASS_START3	:= 0x00c0;
const LANDTILE_GRASS_END3	:= 0x00c3;
const LANDTILE_GRASS_START4	:= 0x00d8;
const LANDTILE_GRASS_END4	:= 0x00db;
const LANDTILE_JUNGLE_START1	:= 0x00ac;
const LANDTILE_JUNGLE_END1	:= 0x00bf;
const LANDTILE_ROCK_START1	:= 0x00e4;
const LANDTILE_ROCK_END1	:= 0x00e7;
const LANDTILE_SAND_START	:= 0x0016;
const LANDTILE_SAND_END		:= 0x004b;
const LANDTILE_WATER_START1	:= 0x00a8;
const LANDTILE_WATER_END1	:= 0x00ab;
