///////////////////////////////////////////////////////////
// MerchantTypes.inc
//
// Merchant types for merchant ai
///////////////////////////////////////////////////////////


const MERCHANTTYPE_ALCHEMIST		:= "alchemist";
const MERCHANTTYPE_ANIMAL_TRAINER	:= "animaltrainer";
const MERCHANTTYPE_ARCHITECT		:= "architect";
const MERCHANTTYPE_ARMORER		:= "armorer";
const MERCHANTTYPE_ARTIST		:= "artist";
const MERCHANTTYPE_BAKER		:= "baker";
const MERCHANTTYPE_BARBER		:= "barber";
const MERCHANTTYPE_BARD			:= "bard";
const MERCHANTTYPE_BARKEEP		:= "barkeep";
const MERCHANTTYPE_BEEKEEPER		:= "beekeeper";
const MERCHANTTYPE_BLACKSMITH		:= "smithingstuffsalesman";
const MERCHANTTYPE_BOOKSELLER		:= "spellbooksalesman";
const MERCHANTTYPE_BOWYER		:= "bowyer";
const MERCHANTTYPE_BUTCHER		:= "butcher";
const MERCHANTTYPE_CARPENTER		:= "carpenter";
const MERCHANTTYPE_COBBLER		:= "cobbler";
const MERCHANTTYPE_FARMER		:= "farmer";
const MERCHANTTYPE_FISHERMAN		:= "fisherman";
const MERCHANTTYPE_FLORIST		:= "florist";
const MERCHANTTYPE_GARDENER		:= "gardener";
const MERCHANTTYPE_INNKEEP		:= "innkeep";
const MERCHANTTYPE_JEWELER		:= "jeweler";
const MERCHANTTYPE_LEATHERWORKER	:= "leatherworker";
const MERCHANTTYPE_MAGE			:= "mage";
const MERCHANTTYPE_MAPMAKER		:= "mapmaker";
const MERCHANTTYPE_MINER		:= "minerstuff";
const MERCHANTTYPE_PROVISIONER		:= "provisioner";
const MERCHANTTYPE_SCRIBE		:= "scribe";
const MERCHANTTYPE_SHIPWRIGHT		:= "shipwright";
const MERCHANTTYPE_TAILOR		:= "tailor";
const MERCHANTTYPE_THIEF		:= "thief";
const MERCHANTTYPE_TINKER		:= "tinker";
const MERCHANTTYPE_VEGETABLE_SELLER	:= "vegseller";
const MERCHANTTYPE_WAITER		:= "waiter";
const MERCHANTTYPE_WAITRESS		:= "waitress";
const MERCHANTTYPE_WEAPONSMITH		:= "weaponsmith";

const MERCHANTTYPE_DEFAULT		:= MERCHANTTYPE_MAGE;