///////////////////////////////////////////////////////////
// MountIDs.inc
//
// Contain the internally used numbers for the mounts
// graphics. Don't change those, hard coded.
///////////////////////////////////////////////////////////


const MOUNTID_ENERGY_VORTEX	:= 0x3ea7;
const MOUNTID_HORSE_DARK_BROWN	:= 0x3ea2;
const MOUNTID_HORSE_GRAY_BROWN	:= 0x3ea1;
const MOUNTID_HORSE_LIGHT_BROWN	:= 0x3e9f;
const MOUNTID_HORSE_LIGHT_GRAY	:= 0x3ea0;
const MOUNTID_LLAMA		:= 0x3ea6;
const MOUNTID_OSTARD_DESERT	:= 0x3ea3;
const MOUNTID_OSTARD_FOREST	:= 0x3ea5;
const MOUNTID_OSTARD_FRENZIED	:= 0x3ea4;