///////////////////////////////////////////////////////////
// NpcAI.inc
//
// Constants for all the npc ai scripts
///////////////////////////////////////////////////////////


const NPCAI_ANIMAL		:= "animal";
const NPCAI_ANIMAL_TRAINER	:= "animaltrainer";
const NPCAI_ARCHER_KILL_PCS	:= "archerkillpcs";
const NPCAI_AUCTIONER		:= "auctioner";
const NPCAI_BANKER		:= "banker";
const NPCAI_BARBER		:= "barber";
const NPCAI_BARKER		:= "barker";
const NPCAI_CAT			:= "cat";
const NPCAI_CHICKEN		:= "chicken";
const NPCAI_CRIER		:= "crier";
const NPCAI_CRITTER_HEALER	:= "critterhealer";
// const NPCAI_DRAGON		:= "dragon"; not in yet
const NPCAI_FIRE_BREATHER	:= "firebreather";
const NPCAI_GAMBLER		:= "gambler";
const NPCAI_GOOD_CASTER		:= "goodcaster";
const NPCAI_GUARD		:= "instakillguard";
const NPCAI_HEALER		:= "daves_healer";
const NPCAI_HELP_PCS		:= "helppcs";
const NPCAI_HIGH_PRIEST		:= "highpriest";
const NPCAI_HUMUC		:= "humuc";
const NPCAI_IMMOBILE		:= "immobile";
const NPCAI_IMMOBILE_SPELL	:= "immobilespell";
const NPCAI_KILL_ANY		:= "killany";
const NPCAI_KILL_PCS		:= "killpcs";
const NPCAI_MERCHANT		:= "merchant";
const NPCAI_PLAYER_MERCHANT	:= "playermerchant";
const NPCAI_QUESTIE		:= "questie";
const NPCAI_ROCK_THROWER	:= "rockthrower";
const NPCAI_SLIME		:= "slime";
const NPCAI_SPIDER		:= "spiders";
const NPCAI_SPELL_KILL_PCS	:= "spellkillpcs";
const NPCAI_TAMED		:= "tamed";
const NPCAI_TRAVELER		:= "traveler";
const NPCAI_VORTEX		:= "vortexai";