///////////////////////////////////////////////////////////
// NpcTemplates.inc
//
// Npc template constants, for the most used templates
// Template for them is NPCTEMPLATE_<desc>_<graphic>
///////////////////////////////////////////////////////////


const NPCTEMPLATE_ALLIGATOR		:= "alligator";
const NPCTEMPLATE_BEAR			:= "bear";
const NPCTEMPLATE_BEAR_BLACK		:= "blackbear";
const NPCTEMPLATE_BEAR_POLAR		:= "polar";
const NPCTEMPLATE_BIRD			:= "bird";
const NPCTEMPLATE_BLADE_SPIRIT		:= "bladespirit";
const NPCTEMPLATE_BULL			:= "bull";
const NPCTEMPLATE_CAT			:= "cat";
const NPCTEMPLATE_CHICKEN		:= "chicken";
const NPCTEMPLATE_COW			:= "cow";
const NPCTEMPLATE_DAEMON		:= "daemon";
const NPCTEMPLATE_DEER			:= "deer";
const NPCTEMPLATE_DOG			:= "dog";
const NPCTEMPLATE_EAGLE			:= "eagle";
const NPCTEMPLATE_ELEMENTAL_AIR		:= "airelemental";
const NPCTEMPLATE_ELEMENTAL_EARTH	:= "earthelemental";
const NPCTEMPLATE_ELEMENTAL_FIRE	:= "fireelemental";
const NPCTEMPLATE_ELEMENTAL_WATER	:= "waterelemental";
const NPCTEMPLATE_ELEMENTAL_LORD_AIR	:= "airelementallord";
const NPCTEMPLATE_ELEMENTAL_LORD_EARTH	:= "earthelementallord";
const NPCTEMPLATE_ELEMENTAL_LORD_FIRE	:= "fireelementallord";
const NPCTEMPLATE_ELEMENTAL_LORD_WATER	:= "waterelementallord";
const NPCTEMPLATE_ENERGY_VORTEX		:= "vortex";
const NPCTEMPLATE_GHOST			:= "ghost";
const NPCTEMPLATE_GOAT			:= "goat";
const NPCTEMPLATE_GORILLA		:= "gorilla";
const NPCTEMPLATE_GREMLIN		:= "gremlin";
const NPCTEMPLATE_GRIZZLY		:= "grizzly";
const NPCTEMPLATE_GUARD			:= "guard";
const NPCTEMPLATE_HARPY			:= "harpy";
const NPCTEMPLATE_HART			:= "hart";
const NPCTEMPLATE_HEADLESS		:= "headless";
const NPCTEMPLATE_HILDISVINI		:= "hildisvini";
const npctemplate_horse_0xc8		:= "horse";
const npctemplate_horse_0xcc		:= "horse2";
const NPCTEMPLATE_HUMUC			:= "humuc";
const NPCTEMPLATE_IMP			:= "imp";
const NPCTEMPLATE_LICHE			:= "liche";
const NPCTEMPLATE_LICHE_BLOOD		:= "bloodliche";
const NPCTEMPLATE_LICHE_LORD		:= "lichelord";
const NPCTEMPLATE_MONGBAT		:= "mongbat";
const NPCTEMPLATE_OSTARD_FOREST		:= "forestostard";
const NPCTEMPLATE_PANTHER		:= "panther";
const NPCTEMPLATE_PIG			:= "pig";
const NPCTEMPLATE_RABBIT		:= "rabbit";
const NPCTEMPLATE_RAT_GIANT		:= "grat";
const NPCTEMPLATE_REAPER		:= "reaper";
const NPCTEMPLATE_SCORPION_GIANT	:= "scorp";
const NPCTEMPLATE_SERPENT_GIANT		:= "giantserpent";
const NPCTEMPLATE_SHADE			:= "shade";
const NPCTEMPLATE_SHEEP			:= "sheep";
const NPCTEMPLATE_SKELETON		:= "skeleton";
const NPCTEMPLATE_SLIME			:= "slime";
const NPCTEMPLATE_SNAKE			:= "snake";
const NPCTEMPLATE_SPIDER_GIANT		:= "spider";
const NPCTEMPLATE_TOWN_PERSON		:= "townperson";
const NPCTEMPLATE_WISP			:= "wisp";
const NPCTEMPLATE_WOLF			:= "wolf";
const NPCTEMPLATE_WOLF_DIRE		:= "direwolf";
const NPCTEMPLATE_WOLF_FROST		:= "frostwolf";
const NPCTEMPLATE_ZOMBIE		:= "zombie";