///////////////////////////////////////////////////////////
//
// OnHitscripts.inc
// 
// Constants for all the onhitscripts
///////////////////////////////////////////////////////////

const ONHITSCRIPT_MAIN		:= 0x0;
const ONHITSCRIPT_AVENGING	:= 0x1;
const ONHITSCRIPT_BANISHING	:= 0x2;
const ONHITSCRIPT_BLINDING	:= 0x3;
const ONHITSCRIPT_BOUNCING	:= 0x4;
const ONHITSCRIPT_DEFLECTION	:= 0x5;
const ONHITSCRIPT_DRAIN_MANA	:= 0x6;
const ONHITSCRIPT_DRAIN_STAMINA	:= 0x7;
const ONHITSCRIPT_INVISIBLE	:= 0x8;
const ONHITSCRIPT_PARALYZE	:= 0x9;
const ONHITSCRIPT_PIERCING_RES	:= 0xa;
const ONHITSCRIPT_POISON	:= 0xb;
const ONHITSCRIPT_RACE_RESIST	:= 0xc;
const ONHITSCRIPT_SPELL_CASTING	:= 0xd;
const ONHITSCRIPT_TRI_ELEMENTAL	:= 0xe;