///////////////////////////////////////////////////////////
// Privilegeids.inc
//
// Constants for all the privileges
///////////////////////////////////////////////////////////


const PRIVILEGEID_ALL			:= "all";
const PRIVILEGEID_DOUBLE_CLICK_ANY	:= "dblclickany";
const PRIVILEGEID_DYE_ANY		:= "dyeany";
const PRIVILEGEID_HEAR_GHOSTS		:= "hearghosts";
const PRIVILEGEID_IGNORE_DOORS		:= "ignoredoors";
const PRIVILEGEID_INVULNERABLE		:= "invul";
const PRIVILEGEID_LOS_ANY		:= "losany";
const PRIVILEGEID_MOVE_ANY		:= "moveany";
const PRIVILEGEID_SEE_GHOSTS		:= "seeghosts";
const PRIVILEGEID_SEE_HIDDEN		:= "seehidden";
const PRIVILEGEID_SEE_INVISIBLE_ITEMS	:= "seeinvisitems";