///////////////////////////////////////////////////////////
// RaceIDs.inc
//
// Constants for all the possible script names.
///////////////////////////////////////////////////////////


const RACEID_BARBARIAN	:= "barbarian";
const RACEID_DARK_ELF	:= "dark elf";
const RACEID_DWARF	:= "dwarf";
const RACEID_ELF	:= "elf";
const RACEID_GOBLIN	:= "goblin";
const RACEID_HUMAN	:= "human";
const RACEID_ORC	:= "orc";
const RACEID_FROST_ELF	:= "frost elf";

const RACEID_DEFAULT	:= RACEID_HUMAN;