///////////////////////////////////////////////////////////
// Scriptnames.inc
//
// Constants for all the possible script names.
///////////////////////////////////////////////////////////


const SCRIPTID_AUCTION_MANAGER		:= ":auction:auctionmanager";
const SCRIPTID_CALL_GUARDS		:= ":areas:callguards";
const SCRIPTID_EFFECT_ASTRAL_INCAPACITY	:= ":astralfights:astralincapacity";
const SCRIPTID_EFFECT_DRUNK		:= ":cooking:drunk";
const SCRIPTID_EFFECT_EXPLOSION_POTION	:= ":alchemy:exploder";
const SCRIPTID_EFFECT_POISON		:= ":mods:poisoneffect";
const SCRIPTID_EFFECT_MOBILE_SUMMONING	:= ":summoning:summoning";
const SCRIPTID_EFFECT_NPC_SUMMONING	:= ":summoning:npcsummoning";
const SCRIPTID_EFFECT_REACTIVE_ARMOR	:= ":combat:reactivearmoronhit";
const SCRIPTID_FX_GRAPHIC_CHANGE	:= ":shilfx:graphicchange";
const SCRIPTID_FX_ITEM_APPEAR		:= ":shilfx:itemappear";
const SCRIPTID_FX_MAGIC_CIRCLE		:= ":shilfx:magiccircleappear";
const SCRIPTID_FX_WATERFALL		:= ":shilfx:waterfallappear";
const SCRIPTID_HOUSE_MANAGEMENT_MENU	:= ":housing:housemenu";
const SCRIPTID_ITEM_DESTROYER		:= ":shilitems:itemdestroyer";
const SCRIPTID_ITEM_RETURNER		:= ":shilitems:itemreturner";
const SCRIPTID_LISTS_MANAGER		:= ":players:listsmanager";
const SCRIPTID_LOOT_CREATION		:= ":loot:lootcreation";
const SCRIPTID_MAIN_DESTROY		:= "::maindestroy";
const SCRIPTID_MAIN_UNEQUIP		:= "::mainunequip";
const SCRIPTID_MAIN_UNEQUIP_WEAPON	:= "::mainweaponunequip";
const SCRIPTID_MOBILE_AREABAN		:= ":areas:areaban";
const SCRIPTID_MOBILE_HUNGER		:= ":cooking:hunger";
const SCRIPTID_MODS_NAME		:= ":mods:namemod";
const SCRIPTID_MODS_PERSISTED		:= ":mods:persistedmod";
const SCRIPTID_MODS_POLYMORPH		:= ":mods:polymorphmod";
const SCRIPTID_MODS_PROTECTION		:= ":mods:protectionmod";
const SCRIPTID_MODS_REGENERATION	:= ":mods:regenmod";
const SCRIPTID_MODS_TEMPORARY		:= ":mods:tempmod";
const SCRIPTID_NPC_DRESSING		:= "::/misc/dressme";
const SCRIPTID_PASSIVE_MEDITATION	:= ":meditation:passivemeditation";
const SCRIPTID_PLAYERS_SCRIPTS		:= ":players:playermanager";
const SCRIPTID_RISE			:= "misc/rise";
const SCRIPTID_SYSTEM_DESTROY		:= ":teleporters:systemdestroy";
const SCRIPTID_TRAP			:= ":traps:traps";
const SCRIPTID_VETERINARY		:= ":veterinary:vet";