/////////////////////////////////////////////////////////////////////
// SkillNames.inc
//
// Contain all the skill names, thos must fit the names defined in
// starteqp.cfg
/////////////////////////////////////////////////////////////////////


const SKILLNAME_ALCHEMY           := "Alchemy";
const SKILLNAME_ANATOMY           := "Anatomy";
const SKILLNAME_ANIMALLORE        := "AnimalLore";
const SKILLNAME_ITEMID            := "ItemId";
const SKILLNAME_ARMSLORE          := "ArmsLore";
const SKILLNAME_PARRY             := "Parry";
const SKILLNAME_BEGGING           := "Begging";
const SKILLNAME_BLACKSMITHY       := "Blacksmithy";
const SKILLNAME_BOWCRAFT          := "Bowcraft";
const SKILLNAME_PEACEMAKING       := "Peacemaking";
const SKILLNAME_CAMPING           := "Camping";
const SKILLNAME_CARPENTRY         := "Carpentry";
const SKILLNAME_CARTOGRAPHY       := "Cartography";
const SKILLNAME_COOKING           := "Cooking";
const SKILLNAME_DETECTINGHIDDEN   := "DetectingHidden";
const SKILLNAME_ENTICEMENT        := "Enticement";
const SKILLNAME_EVALINT           := "EvaluatingIntelligence";
const SKILLNAME_HEALING           := "Healing";
const SKILLNAME_FISHING           := "Fishing";
const SKILLNAME_FORENSICS         := "ForensicEval";
const SKILLNAME_HERDING           := "Herding";
const SKILLNAME_HIDING            := "Hiding";
const SKILLNAME_PROVOCATION       := "Provocation";
const SKILLNAME_INSCRIPTION       := "Inscription";
const SKILLNAME_LOCKPICKING       := "Lockpicking";
const SKILLNAME_MAGERY            := "Magery";
const SKILLNAME_MAGICRESISTANCE   := "MagicResistance";
const SKILLNAME_TACTICS           := "Tactics";
const SKILLNAME_SNOOPING          := "Snooping";
const SKILLNAME_MUSICIANSHIP      := "Musicianship";
const SKILLNAME_POISONING         := "Poisoning";
const SKILLNAME_ARCHERY           := "Archery";
const SKILLNAME_SPIRITSPEAK       := "SpiritSpeak";
const SKILLNAME_STEALING          := "Stealing";
const SKILLNAME_TAILORING         := "Tailoring";
const SKILLNAME_TAMING            := "AnimalTaming";
const SKILLNAME_TASTEID           := "TasteIdentification";
const SKILLNAME_TINKERING         := "Tinkering";
const SKILLNAME_TRACKING          := "Tracking";
const SKILLNAME_VETERINARY        := "Veterinary";
const SKILLNAME_SWORDSMANSHIP     := "Swordsmanship";
const SKILLNAME_MACEFIGHTING      := "MaceFighting";
const SKILLNAME_FENCING           := "Fencing";
const SKILLNAME_WRESTLING         := "Wrestling";
const SKILLNAME_LUMBERJACKING     := "Lumberjacking";
const SKILLNAME_MINING            := "Mining";
const SKILLNAME_MEDITATION        := "Meditation";
const SKILLNAME_STEALTH           := "Stealth";
const SKILLNAME_REMOVETRAP        := "RemoveTrap";