/////////////////////////////////////////////////////////////////////
// UsescriptIDs.inc
//
// Contain the most used usescripts, more than likely put only
// those that are modified directly from inside scripts there.
/////////////////////////////////////////////////////////////////////


const USESCRIPTID_DRINK			:= ":cooking:drink";
const USESCRIPTID_EAT			:= ":cooking:eat";
const USESCRIPTID_SECURE_CONTAINER	:= ":housing:securecont";
const USESCRIPTID_SHRUNK_DOLLY_AREA	:= ":shrunk:shrunkarea";
const USESCRIPTID_SHRUNK_DOLLY_ITEM	:= ":shrunk:shrunkitem";
const USESCRIPTID_SHRUNK_DOLLY_NPC	:= ":shrunk:shrunknpc";
const USESCRIPTID_SHRUNK_DOLLY_SPAWN	:= ":shrunk:shrunkspawn";
const USESCRIPTID_TRAPPED_CONTAINER	:= ":traps:traps";