//////////////////////////////////////////////////////////////////////////
// Constants.inc
//
// Constants for all the constants defined in the constants folder
//////////////////////////////////////////////////////////////////////////


//include "include/constants/anims";
include "include/constants/attributeids";
include "include/constants/cfgfiles";
//include "include/constants/cids";
include "include/constants/cmdlevels";
//include "include/constants/colors";
include "include/constants/creaturetypes";
include "include/constants/datastorefiles";
include "include/constants/eventids";
//include "include/constants/facings";
//include "include/constants/fonts";
//include "include/constants/fxs";
include "include/constants/gumpids";
include "include/constants/hitscripts";
include "include/constants/itemids";
//include "include/constants/layers";
include "include/constants/locations";
include "include/constants/merchanttypes";
include "include/constants/mountids";
include "include/constants/multiids";
include "include/constants/npcai";
include "include/constants/npcdata";
include "include/constants/npctemplates";
//include "include/constants/objtypes";
include "include/constants/privilegeids";
include "include/constants/propids";
include "include/constants/raceids";
include "include/constants/resourceids";
include "include/constants/scriptids";
include "include/constants/settings";
//include "include/constants/sfxs";
//include "include/constants/skillids";
include "include/constants/skillnames";
//include "include/constants/spelldata";
include "include/constants/statids";
include "include/constants/storageareas";
include "include/constants/syseventids";
include "include/constants/timeids";
include "include/constants/usescriptids";
include "include/constants/vitalids";