////////////////////////////////////////////////////////////////////////////
//                                                                        //
// event IDs to be returned in eventid member of wait_for_event           //
// result.                                                                //
//                                                                        //
////////////////////////////////////////////////////////////////////////////
//                                                                        //
// eventid.inc                                                            //
//                                                                        //
// Contains users defined events, those must use at least 2 bits,         //
// since sysevent.inc use one bit events.                                 //
//                                                                        //
// Maintainer : Shilohen                                                  //
//                                                                        //
////////////////////////////////////////////////////////////////////////////

include "include/constants";