use uo;


function DefineSkillTitlesDictionary()

	var skill := dictionary;

	// Normal skills titles
	skill [ 0 ]	:= "Alchemist";
	skill [ 1 ]	:= "Healer";
	skill [ 2 ]	:= "Ranger";
	skill [ 3 ]	:= "Merchant";
	skill [ 4 ]	:= "Warrior";
	skill [ 5 ]	:= "Shieldsfighter";
	skill [ 6 ]	:= "Beggar";
	skill [ 7 ]	:= "Smith";
	skill [ 8 ]	:= "Bowyer";
	skill [ 9 ]	:= "Bard";
	skill [ 10 ]	:= "Camper";
	skill [ 11 ]	:= "Carpenter";
	skill [ 12 ]	:= "Cartographer";
	skill [ 13 ]	:= "Chef";
	skill [ 14 ]	:= "Scout";
	skill [ 15 ]	:= "Bard";
	skill [ 16 ]	:= "Scholar";
	skill [ 17 ]	:= "Healer";
	skill [ 18 ]	:= "Fisherman";
	skill [ 19 ]	:= "Detective";
	skill [ 20 ]	:= "Shepherd";
	skill [ 21 ]	:= "Rogue";
	skill [ 22 ]	:= "Bard";
	skill [ 23 ]	:= "Scribe";
	skill [ 24 ]	:= "Rogue";
	skill [ 25 ]	:= "Mage";
	skill [ 26 ]	:= "Mage";
	skill [ 27 ]	:= "Warrior";
	skill [ 28 ]	:= "Pickpocket";
	skill [ 29 ]	:= "Bard";
	skill [ 30 ]	:= "Assassin";
	skill [ 31 ]	:= "Archer";
	skill [ 32 ]	:= "Medium";
	skill [ 33 ]	:= "Pickpocket";
	skill [ 34 ]	:= "Tailor";
	skill [ 35 ]	:= "Tamer";
	skill [ 36 ]	:= "Chef";
	skill [ 37 ]	:= "Tinker";
	skill [ 38 ]	:= "Ranger";
	skill [ 39 ]	:= "Healer";
	skill [ 40 ]	:= "Swordsman";
	skill [ 41 ]	:= "Armsman";
	skill [ 42 ]	:= "Fencer";
	skill [ 42 ]	:= "Wrestler";
	skill [ 44 ]	:= "Lumberjack";
	skill [ 45 ]	:= "Miner";
	skill [ 46 ]	:= "Stoic";
	skill [ 47 ]	:= "Rogue";
	skill [ 48 ]	:= "Rogue";


	// Classe skill titles
	skill [ 49 ]	:= "Minstrel";
	skill [ 50 ]	:= "Artisant";
	skill [ 51 ]	:= "Wizard";
	skill [ 52 ]	:= "Hunter";
	skill [ 53 ]	:= "Thief";
	skill [ 54 ]	:= "Warlord";

	return skill;

endfunction


function DefineSkillLevelTitlesDictionary()

	var level := dictionary;

	level [ 1 ]	:= "Neophyte";
	level [ 2 ]	:= "Novice";
	level [ 3 ]	:= "Apprentice";
	level [ 4 ]	:= "Journeyman";
	level [ 5 ]	:= "Expert";
	level [ 6 ]	:= "Adept";
	level [ 7 ]	:= "Master";
	level [ 8 ]	:= "Grandmaster";
	level [ 9 ]	:= "Legendary";

	return level;

endfunction