// GAMELIST.INC
//
// Creator: Myrathi <tjh@myrathi.co.uk>
// Created: 25-Apr-2001

include "gumpids";

// Build Array - Backgammon
//
var zba_backgammon := {
	{"W",	GID_WHITECHECKER},
	{"B",	GID_BLACKCHECKER}
};

// Build Array - Chess
//
var zba_chess := {
	{"P",	GID_WHITEPAWN},		// upper case
	{"N",	GID_WHITEKNIGHT},
	{"B",	GID_WHITEBISHOP},
	{"R",	GID_WHITEROOK},
	{"K",	GID_WHITEKING},
	{"Q",	GID_WHITEQUEEN},
	{"p",	GID_BLACKPAWN},		// lower case
	{"n",	GID_BLACKKNIGHT},
	{"b",	GID_BLACKBISHOP},
	{"r",	GID_BLACKROOK},
	{"k",	GID_BLACKKING},
	{"q",	GID_BLACKQUEEN}
};